@traitdef HasJac{F}
@traitdef HastGrad{F}
@traitdef HasParamFuncs{F}
@traitdef HasParamDeriv{F}
@traitdef HasParamJac{F}
@traitdef HasInvJac{F}
@traitdef HasInvW{F}
@traitdef HasInvW_t{F}
@traitdef HasHes{F}
@traitdef HasInvHes{F}
